### ISSUE TITLE
Install error (Class not found)

### ISSUE THREAD

**Issue by coret** [sinanatra/NestedDataTypes#13]
To investigate https://github.com/sinanatra/NestedDataTypes/issues/12 I made a fresh install of Omeka S 3.2.2 (clean DB, no modules) and tried to install [version 3.3.0](https://github.com/sinanatra/NestedDataTypes/releases/tag/v3.3.0) of the NestedDataTypes module. I put de contents of the ZIP in the modules/NestedDataTypes directory. When I click on the Install button in Omeka S admin an error occurs, the application log shows the following:

```
2022-08-02T15:47:16+00:00 ERR (3): Error: Class 'NestedDataTypes\Module' not found in /home/http/gtm.coret.org/ont/application/src/Module/Manager.php:368
Stack trace:
#0 /home/http/gtm.coret.org/ont/application/src/Module/Manager.php(239): Omeka\Module\Manager->getModuleObject()
#1 /home/http/gtm.coret.org/ont/application/src/Controller/Admin/ModuleController.php(117): Omeka\Module\Manager->install()
#2 /home/http/gtm.coret.org/ont/vendor/laminas/laminas-mvc/src/Controller/AbstractActionController.php(77): Omeka\Controller\Admin\ModuleController->installAction()
#3 /home/http/gtm.coret.org/ont/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\Controller\AbstractActionController->onDispatch()
#4 /home/http/gtm.coret.org/ont/vendor/laminas/laminas-eventmanager/src/EventManager.php(178): Laminas\EventManager\EventManager->triggerListeners()
#5 /home/http/gtm.coret.org/ont/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(103): Laminas\EventManager\EventManager->triggerEventUntil()
#6 /home/http/gtm.coret.org/ont/vendor/laminas/laminas-mvc/src/DispatchListener.php(139): Laminas\Mvc\Controller\AbstractController->dispatch()
#7 /home/http/gtm.coret.org/ont/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\DispatchListener->onDispatch()
#8 /home/http/gtm.coret.org/ont/vendor/laminas/laminas-eventmanager/src/EventManager.php(178): Laminas\EventManager\EventManager->triggerListeners()
#9 /home/http/gtm.coret.org/ont/vendor/laminas/laminas-mvc/src/Application.php(331): Laminas\EventManager\EventManager->triggerEventUntil()
#10 /home/http/gtm.coret.org/ont/index.php(21): Laminas\Mvc\Application->run()
#11 {main}

```

I also tried version 3.2.2 and 3.2.1, with resulted in the same error. Even after I installed Omeka S 3.1.2 (with clean DB) the install error occured.

**Comment by sinanatra** [comment]
is the folder named as referenced [here](https://github.com/sinanatra/NestedDataTypes/issues/8#issuecomment-892609329)  ? 
It should be `NestedDataType`

**Comment by coret** [comment]
Hmm, maybe some kind of caching issue that bothered me. Because I just wanted to retry the install and V 3.3.0 was already activated. De-activate and activate also just worked.
