### ISSUE TITLE
Error installing module

### ISSUE THREAD

**Issue by coret** [sinanatra/NestedDataTypes#8]
I've downloaded the 3.0.0 release and extracted the contents in the module directory of Omeka-S (version 3.1.0-alpha3). When I try to install the module I get a "Omeka S encountered an error" message. The application log shows the following:

```
2021-08-04T11:54:07+00:00 ERR (3): Error: Class 'NestedDataTypes\Module' not found in /home/xxxxx/omeka-s/application/src/Module/Manager.php:368
Stack trace:
#0 /home/xxxxx/omeka-s/application/src/Module/Manager.php(239): Omeka\Module\Manager->getModuleObject()
#1 /home/xxxxx/omeka-s/application/src/Controller/Admin/ModuleController.php(117): Omeka\Module\Manager->install()
#2 /home/xxxxx/omeka-s/vendor/laminas/laminas-mvc/src/Controller/AbstractActionController.php(77): Omeka\Controller\Admin\ModuleController->installAction()
#3 /home/xxxxx/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\Controller\AbstractActionController->onDispatch()
#4 /home/xxxxx/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(178): Laminas\EventManager\EventManager->triggerListeners()
#5 /home/xxxxx/omeka-s/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(103): Laminas\EventManager\EventManager->triggerEventUntil()
#6 /home/xxxxx/omeka-s/vendor/laminas/laminas-mvc/src/DispatchListener.php(139): Laminas\Mvc\Controller\AbstractController->dispatch()
#7 /home/xxxxx/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\DispatchListener->onDispatch()
#8 /home/xxxxx/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(178): Laminas\EventManager\EventManager->triggerListeners()
#9 /home/xxxxx/omeka-s/vendor/laminas/laminas-mvc/src/Application.php(331): Laminas\EventManager\EventManager->triggerEventUntil()
#10 /home/xxxxx/omeka-s/index.php(21): Laminas\Mvc\Application->run()
#11 {main}
```

**Comment by sinanatra** [comment]
Hello, the module is still a work in progress, so there will be quite some bugs in the upcoming future.
The folder inside modules should be called: `NestedDataType` without the letter s

- modules: 
  - NestedDataType
     - asset
     - config
     - Module.php
     - readme.md
     - src
     - view

**Comment by coret** [comment]
Thanks, renaming the folder was the solution!
